package cliente_banco;

import java.util.Vector;
import org.apache.xmlrpc.XmlRpcClient;

public class Principal extends javax.swing.JFrame {

    String ruta_RPC = "http://localhost:81/";
    Vector<Integer> datos = new Vector<Integer>();
    Vector<Integer> datos2 = new Vector<Integer>();
    int acceso = 0;
    String client = "";
    

    public Principal() {
        initComponents();
        setSize(555, 435);
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 0, 200, 90);

        usuario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(usuario);
        usuario.setBounds(170, 150, 230, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 130, 250, 90);

        jLabel4.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        jLabel4.setText("Contraseña:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 240, 120, 24);

        error.setBackground(new java.awt.Color(255, 255, 255));
        error.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(error);
        error.setBounds(20, 350, 520, 0);

        aceptar.setBackground(new java.awt.Color(102, 255, 102));
        aceptar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(190, 300, 170, 50);

        jLabel6.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        jLabel6.setText("B I E N V E N I D O");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 110, 210, 24);

        pass.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(pass);
        pass.setBounds(170, 230, 230, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 210, 250, 90);

        jLabel7.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        jLabel7.setText("Usuario:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 170, 90, 24);

        mensaje.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(mensaje);
        mensaje.setBounds(30, 360, 490, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if (usuario.getText().isEmpty() && pass.getText().isEmpty()) {
            mensaje.setText("Llene los campos");
        } else {
            String user = usuario.getText();
            String pas = pass.getText().toString();
            datos.addElement(Integer.parseInt(user));
            datos.addElement(Integer.parseInt(pas));
            try {
                XmlRpcClient cliente= new XmlRpcClient(ruta_RPC);
                Object result = cliente.execute("ServerRPC.acceso", datos);

                acceso = (Integer) result;
                mensaje.setText("Entrando...");
                
                if (acceso == 1) {
                    recupera_cuenta(Integer.parseInt(user));
                } else {
                    mensaje.setText("Error de credenciales");
                }
            } catch (Exception e) {
            }

            usuario.setText("");
            pass.setText("");
        }
        datos.clear();
    }//GEN-LAST:event_aceptarActionPerformed

    public void recupera_cuenta(int user) {
        datos2.addElement(user);
        try {
            XmlRpcClient cliente = new XmlRpcClient(ruta_RPC);
            Object result = cliente.execute("ServerRPC.cliente", datos2);
            client = (String) result;
            this.setVisible(false);
            Principal2 on = new Principal2(client,user);
            on.setVisible(true);
        } catch (Exception e) {
            mensaje.setText(""+e.getMessage());
        }
        datos2.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
