package cliente_banco;

import java.util.Vector;
import org.apache.xmlrpc.XmlRpcClient;

/**
 *
 * @author Ivan Luis Jimenez
 */
public class Principal2 extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    String ruta_RPC = "http://localhost:81/";
    Vector<Integer> datos = new Vector<Integer>();
    Vector<Integer> datos2 = new Vector<Integer>();
    Vector<Vector<String>> estado = new Vector<Vector<String>>();
    String client = "";
    int saldo = 0;
    int user = 0;

    public Principal2(String cliente, int user) {
        initComponents();
        setSize(555, 435);
        client = cliente;
        this.user = user;
        mensaje.setText("CLIENTE: " + cliente);
        setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        consultaSaldo = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        salir2 = new javax.swing.JButton();
        cambios = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 0, 190, 112);

        consultaSaldo.setBackground(new java.awt.Color(0, 204, 204));
        consultaSaldo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        consultaSaldo.setText("C O N S U L T A R   S A L D O");
        consultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(consultaSaldo);
        consultaSaldo.setBounds(280, 120, 250, 90);

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton6.setText("R E T I R A R   E F E C T I V O");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(20, 120, 250, 90);

        salir2.setBackground(new java.awt.Color(255, 0, 0));
        salir2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        salir2.setForeground(new java.awt.Color(255, 255, 255));
        salir2.setText("S A L I R");
        salir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salir2ActionPerformed(evt);
            }
        });
        getContentPane().add(salir2);
        salir2.setBounds(280, 230, 250, 90);

        cambios.setBackground(new java.awt.Color(0, 204, 204));
        cambios.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        cambios.setText("V E R   U L T I M O S   C A M B I O S ");
        cambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiosActionPerformed(evt);
            }
        });
        getContentPane().add(cambios);
        cambios.setBounds(20, 230, 250, 90);

        error.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(error);
        error.setBounds(20, 330, 500, 16);

        mensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mensaje.setText("U S U A R I O: ");
        getContentPane().add(mensaje);
        mensaje.setBounds(20, 360, 180, 19);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        retirar on = new retirar(client, user);
        on.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void salir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salir2ActionPerformed
        this.setVisible(false);
        Principal on = new Principal();
        on.setVisible(true);
    }//GEN-LAST:event_salir2ActionPerformed

    private void consultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaSaldoActionPerformed
        int ss = saldo();
        this.setVisible(false);
        String s = String.valueOf(ss);
        saldo on = new saldo(s, client, user);
        on.setVisible(true);
    }//GEN-LAST:event_consultaSaldoActionPerformed

    public int saldo() {
        System.out.println("lol");
        datos.addElement(user);
        try {
            XmlRpcClient cliente = new XmlRpcClient(ruta_RPC);
            Object result = cliente.execute("ServerRPC.saldo", datos);
            saldo = (int) result;
            System.out.println(saldo);
        } catch (Exception e) {
            error.setText("" + e.getMessage());
        }
        datos.clear();
        return saldo;
    }

    private void cambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiosActionPerformed

        datos2.addElement(user);
        try {
            XmlRpcClient cliente = new XmlRpcClient(ruta_RPC);
            Object result = cliente.execute("ServerRPC.estado", datos2);
            estado = (Vector<Vector<String>>) result;
            System.out.println(saldo);
            if (!estado.isEmpty()) {
                this.setVisible(false);
                ultimosCambios on = new ultimosCambios(estado,client,user);
                on.visualizar();
            }else{
                error.setText("No se encontraron datos");
            }

        } catch (Exception e) {
            error.setText("" + e.getMessage());
        }

    }//GEN-LAST:event_cambiosActionPerformed

    public String return_cliente() {
        return client;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Principal2(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cambios;
    private javax.swing.JButton consultaSaldo;
    private javax.swing.JLabel error;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton salir2;
    // End of variables declaration//GEN-END:variables
}
