package cliente_banco;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan Luis Jimenez
 */
public class ultimosCambios extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Vector<String> sA = new Vector<String>();
    Vector<String> re = new Vector<String>();
    Vector<String> fe = new Vector<String>();
    Vector<String> cC = new Vector<String>();
    
    int user = 0;
    String cliente = "";
    public ultimosCambios(Vector<Vector<String>> estado,String client,int user) {
        initComponents();
        setSize(555, 435);
        limpiar();
        cliente = client;
        us.setText("CLIENTE:"+cliente);
        this.user = user;
        sA = estado.get(0);
        re = estado.get(1);
        fe = estado.get(2);
        cC = estado.get(3);
        
        setLocationRelativeTo(this);
    }
    
    public void limpiar(){
        sA.clear();
        re.clear();
        fe.clear();        
        cC.clear();
    }
    
    public void visualizar(){
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        if(!sA.isEmpty()){
            
            for (int i = 0; i <sA.size(); i++) {
                modelo.addRow(new String[]{sA.get(i), re.get(i),fe.get(i),cC.get(i)});
            }
            setVisible(true);
        }else{
            mensaje.setText("No se encontraron datos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        mensaje = new javax.swing.JLabel();
        us = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 0, 200, 112);

        error.setBackground(new java.awt.Color(255, 255, 255));
        error.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(error);
        error.setBounds(20, 350, 520, 0);

        aceptar.setBackground(new java.awt.Color(102, 255, 102));
        aceptar.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(190, 330, 170, 50);

        jLabel6.setFont(new java.awt.Font("Euphemia", 1, 18)); // NOI18N
        jLabel6.setText("U L T I M O S   M O V I M I E N T O S");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 110, 410, 24);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Saldo Anterior", "Retiro", "Fecha", "Cajero"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabla);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 140, 530, 130);

        mensaje.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(mensaje);
        mensaje.setBounds(10, 280, 520, 20);

        us.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        getContentPane().add(us);
        us.setBounds(10, 300, 210, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        Principal2 on = new Principal2(cliente, user);
        on.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ultimosCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ultimosCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ultimosCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ultimosCambios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
     }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}
